# Generated by Django 5.2.6 on 2025-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
